# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('authority_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10000)),
                ('e_mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_no', models.CharField(max_length=10)),
                ('route_no', models.IntegerField()),
                ('strart_destination', models.CharField(max_length=25)),
                ('end_destination', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('add_state', models.BooleanField()),
                ('USERNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('authority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useract.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='TrainDetails',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_no', models.CharField(max_length=10)),
                ('route_no', models.IntegerField()),
                ('strart_destination', models.CharField(max_length=25)),
                ('end_destination', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useract.Report'),
        ),
    ]
