# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reported_date',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reported_time',
            field=models.CharField(default='abc', max_length=10),
            preserve_default=False,
        ),
    ]
