# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0002_auto_20180412_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindetails',
            old_name='train_no',
            new_name='train_name',
        ),
    ]
