# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0003_auto_20180418_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindetails',
            name='train_name',
            field=models.CharField(max_length=100),
        ),
    ]
