# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0004_auto_20180418_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busdetails',
            old_name='strart_destination',
            new_name='start_destination',
        ),
    ]
