# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0006_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
