# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0007_auto_20180504_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='picture',
            field=models.ImageField(upload_to='media/pictures'),
        ),
    ]
