# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0009_auto_20180504_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
