# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('useract', '0010_auto_20180504_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('client', 'client'), ('admin', 'admin'), ('external', 'external')], default='client', max_length=10)),
            ],
        ),
    ]
