# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('class_id_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Classes')),
                ('layer_id_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Layers')),
            ],
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=100000)),
                ('class_bag', models.CharField(max_length=100000000, null=True)),
                ('word_bag', models.CharField(max_length=100000000, null=True)),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.sets')),
            ],
        ),
    ]
