# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_state',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
